In [1]:
import pandas as pd 
import numpy as np 

df = pd.read_csv("../Tascas/Data/DelayedFlights.csv", nrows=10000)

In [2]:
np.corrcoef(df["ArrDelay"], df["DepDelay"])

array([[nan, nan],
       [nan,  1.]])

In [3]:
df.dropna(inplace = True, subset=["ArrDelay", "DepDelay", "DepTime"])
np.corrcoef(df["ArrDelay"], df["DepDelay"])

array([[1.        , 0.95478414],
       [0.95478414, 1.        ]])

In [4]:
df.head()

Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0           0  2008      1           3          4   2003.0        1955   
1           1  2008      1           3          4    754.0         735   
2           2  2008      1           3          4    628.0         620   
3           4  2008      1           3          4   1829.0        1755   
4           5  2008      1           3          4   1940.0        1915   

   ArrTime  CRSArrTime UniqueCarrier  ...  TaxiIn TaxiOut  Cancelled  \
0   2211.0        2225            WN  ...     4.0     8.0          0   
1   1002.0        1000            WN  ...     5.0    10.0          0   
2    804.0         750            WN  ...     3.0    17.0          0   
3   1959.0        1925            WN  ...     3.0    10.0          0   
4   2121.0        2110            WN  ...     4.0    10.0          0   

   CancellationCode  Diverted  CarrierDelay  WeatherDelay NASDelay  \
0                 N         0           NaN           NaN      NaN   
1                 N         0           NaN           NaN      NaN   
2                 N         0           NaN           NaN      NaN   
3                 N         0           2.0           0.0      0.0   
4                 N         0           NaN           NaN      NaN   

  SecurityDelay  LateAircraftDelay  
0           NaN                NaN  
1           NaN                NaN  
2           NaN                NaN  
3           0.0               32.0  
4           NaN                NaN  

[5 rows x 30 columns]

In [5]:
np.corrcoef([df["ArrDelay"], df["DepDelay"], df["DepTime"]])

array([[1.        , 0.95478414, 0.28460667],
       [0.95478414, 1.        , 0.29664147],
       [0.28460667, 0.29664147, 1.        ]])

In [6]:
df.drop(inplace = True, columns = ["Year","Cancelled", "Diverted"])

In [7]:
df.corr()

Unnamed: 0  Month  DayofMonth  DayOfWeek   DepTime  \
Unnamed: 0           1.000000    NaN    0.991420  -0.358006 -0.020227   
Month                     NaN    NaN         NaN        NaN       NaN   
DayofMonth           0.991420    NaN    1.000000  -0.349091 -0.018495   
DayOfWeek           -0.358006    NaN   -0.349091   1.000000  0.075997   
DepTime             -0.020227    NaN   -0.018495   0.075997  1.000000   
CRSDepTime          -0.001892    NaN    0.001141   0.064448  0.980572   
ArrTime              0.023886    NaN    0.024008   0.051154  0.551090   
CRSArrTime           0.003763    NaN    0.003639   0.050873  0.756413   
FlightNum           -0.004143    NaN   -0.006856   0.000223  0.018485   
ActualElapsedTime   -0.033342    NaN   -0.029409   0.004454 -0.132874   
CRSElapsedTime      -0.031458    NaN   -0.027395   0.001990 -0.131922   
AirTime             -0.027406    NaN   -0.022923  -0.001857 -0.128464   
ArrDelay            -0.113298    NaN   -0.121096   0.063465  0.284607   
DepDelay            -0.119733    NaN   -0.127570   0.063678  0.296641   
Distance            -0.028543    NaN   -0.025791  -0.001005 -0.119529   
TaxiIn              -0.078881    NaN   -0.082625   0.072505  0.044816   
TaxiOut             -0.015699    NaN   -0.018062   0.018176 -0.088113   
CarrierDelay        -0.043122    NaN   -0.038562   0.017792 -0.018099   
WeatherDelay         0.012703    NaN    0.012033  -0.024533 -0.030768   
NASDelay             0.029754    NaN    0.026635  -0.027724 -0.077938   
SecurityDelay        0.053417    NaN    0.051257   0.018307 -0.043389   
LateAircraftDelay   -0.084005    NaN   -0.092395   0.032443  0.292759   

                   CRSDepTime   ArrTime  CRSArrTime  FlightNum  \
Unnamed: 0          -0.001892  0.023886    0.003763  -0.004143   
Month                     NaN       NaN         NaN        NaN   
DayofMonth           0.001141  0.024008    0.003639  -0.006856   
DayOfWeek            0.064448  0.051154    0.050873   0.000223   
DepTime              0.980572  0.551090    0.756413   0.018485   
CRSDepTime           1.000000  0.559755    0.771256   0.021198   
ArrTime              0.559755  1.000000    0.736689   0.001376   
CRSArrTime           0.771256  0.736689    1.000000   0.001211   
FlightNum            0.021198  0.001376    0.001211   1.000000   
ActualElapsedTime   -0.140086 -0.080151   -0.047465   0.047767   
CRSElapsedTime      -0.138437 -0.081580   -0.043553   0.055050   
AirTime             -0.134079 -0.078069   -0.042772   0.050287   
ArrDelay             0.189586  0.008568    0.116944  -0.027203   
DepDelay             0.196026  0.001427    0.128518  -0.013163   
Distance            -0.126816 -0.087814   -0.038487   0.042765   
TaxiIn               0.041156  0.055824    0.048695  -0.007116   
TaxiOut             -0.102076 -0.064191   -0.079181  -0.011715   
CarrierDelay        -0.070309 -0.048106   -0.048740   0.017464   
WeatherDelay        -0.063441 -0.031344   -0.048994  -0.001503   
NASDelay            -0.097336 -0.048832   -0.079375  -0.015651   
SecurityDelay       -0.042242 -0.015185   -0.024281  -0.007453   
LateAircraftDelay    0.223953 -0.031730    0.147308  -0.009518   

                   ActualElapsedTime  ...  ArrDelay  DepDelay  Distance  \
Unnamed: 0                 -0.033342  ... -0.113298 -0.119733 -0.028543   
Month                            NaN  ...       NaN       NaN       NaN   
DayofMonth                 -0.029409  ... -0.121096 -0.127570 -0.025791   
DayOfWeek                   0.004454  ...  0.063465  0.063678 -0.001005   
DepTime                    -0.132874  ...  0.284607  0.296641 -0.119529   
CRSDepTime                 -0.140086  ...  0.189586  0.196026 -0.126816   
ArrTime                    -0.080151  ...  0.008568  0.001427 -0.087814   
CRSArrTime                 -0.047465  ...  0.116944  0.128518 -0.038487   
FlightNum                   0.047767  ... -0.027203 -0.013163  0.042765   
ActualElapsedTime           1.000000  ... -0.039859 -0.006190  0.96582

In [8]:
df.drop(inplace = True, columns = ["Month"])
corr = round(df.corr(),3)
corr.style.bacground_gradient()

AttributeError: 'Styler' object has no attribute 'bacground_gradient'

In [ ]:
#TEST CHI-CUADRADO

In [9]:
import pandas as pd 
import numpy as np 

df = pd.read_csv("../Tascas/Data/DelayedFlights.csv", nrows=100000)

In [10]:
np.random.seed(0)
df = df[df["Origin"].isin(["HOU","ATL","IND"])]
df = df.sample(frac=1)
df = df[0:1000]

In [12]:
df["BigDelay"] = df["ArrDelay"] >30
observados = pd.crosstab(index=df['BigDelay'], columns=df['Origin'], margins= True)

In [13]:
observados

Origin    ATL  HOU  IND   All
BigDelay                     
False     336  269   36   641
True      217  110   32   359
All       553  379   68  1000

In [14]:
from scipy.stats import chi2_contingency

In [15]:
test = chi2_contingency(observados)

In [16]:
test

(14.148521571972086,
 0.028020388668468777,
 6,
 array([[ 354.473,  242.939,   43.588,  641.   ],
        [ 198.527,  136.061,   24.412,  359.   ],
        [ 553.   ,  379.   ,   68.   , 1000.   ]]))

In [17]:
esperados = pd.DataFrame(test[3])

In [18]:
esperados

0        1       2       3
0  354.473  242.939  43.588   641.0
1  198.527  136.061  24.412   359.0
2  553.000  379.000  68.000  1000.0

In [20]:
esperados_rel = round(esperados.apply(lambda r: r/len(df) *100, axis=1),2)

In [21]:
observados_rel = round(observados.apply(lambda r: r/len(df) *100, axis=1),2)

In [22]:
observados_rel

Origin     ATL   HOU  IND    All
BigDelay                        
False     33.6  26.9  3.6   64.1
True      21.7  11.0  3.2   35.9
All       55.3  37.9  6.8  100.0

In [23]:
esperados_rel

0      1     2      3
0  35.45  24.29  4.36   64.1
1  19.85  13.61  2.44   35.9
2  55.30  37.90  6.80  100.0

In [24]:
test[1]

0.028020388668468777

In [26]:
#valor < 0.05 hay diferencias significativas
#valor > 0.05 no hay diferencias significativas


In [27]:
#OUTLAYERS
import pandas as pd 
import numpy as np 

df = pd.read_csv("../Tascas/Data/DelayedFlights.csv", nrows=100000)

In [29]:
x= df["ArrDelay"].dropna()

In [30]:
Q1 = np.percentile(x,25)
Q3 = np.percentile(x,75)

In [31]:
rangointer = Q3 -Q1

In [34]:
umbralsuperior = Q3 + 1.5*rangointer
umbralinferior = Q1 - 1.5*rangointer

In [35]:
umbralsuperior

129.0

In [37]:
umbralinferior

-63.0

In [38]:
np.mean(x > umbralsuperior)

0.07358812318186378

In [39]:
np.mean(x < umbralinferior)

2.0062192797672787e-05

In [40]:
from sklearn.covariance import  EllipticEnvelope

In [48]:
outliers = EllipticEnvelope(contamination = .01)

In [49]:
var_list = ["DepDelay", "TaxiIn", "TaxiOut", "CarrierDelay","WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay"]

In [50]:
x = np.array(df.loc[:,var_list].dropna())

In [51]:
outliers.fit(x)

EllipticEnvelope(contamination=0.01)

In [52]:
pred = outliers.predict(x)

In [53]:
pred

array([1, 1, 1, ..., 1, 1, 1])

In [54]:
elip_outliers = np.where(pred == -1)[0]

In [55]:
elip_outliers

array([   18,    56,   269,   272,   614,   615,   616,  1767,  1821,
        2177,  2233,  2413,  2600,  2613,  2621,  2629,  2704,  3283,
        3546,  3590,  3666,  3679,  3686,  3791,  3831,  3895,  4058,
        4148,  4338,  4710,  5532,  5648,  5650,  5651,  5658,  5659,
        5660,  5661,  5662,  5664,  5669,  5673,  5697,  6311,  6312,
        6511,  6513,  6515,  6516,  6520,  6527,  6868,  8135,  8475,
        8885,  9030,  9074,  9081,  9193,  9199,  9447,  9472,  9992,
       10002, 11584, 12046, 12047, 12049, 12303, 12359, 12692, 12938,
       13013, 13459, 13515, 13518, 13643, 13669, 13767, 13845, 14408,
       14726, 15204, 15763, 16105, 16138, 16142, 16199, 16219, 16301,
       16305, 17051, 17221, 17238, 17472, 17516, 17532, 17538, 17580,
       17585, 17587, 18041, 18059, 18063, 18075, 18097, 18348, 18366,
       18381, 18447, 18497, 18592, 18638, 18812, 18941, 19011, 19043,
       19278, 19295, 19408, 19434, 19541, 19558, 19673, 19717, 19800,
       19862, 19888,