In [1]:
from sklearn import preprocessing
import pandas as pd 
import numpy as np 

df = pd.read_csv("../../Tascas/Data/DelayedFlights.csv", nrows=100000)
df = df[["ArrDelay","DepDelay","Distance","AirTime"]].dropna()

In [3]:
# Escalar por estarandizacion

X_scaled = preprocessing.scale(df)
X_scaled


array([[-1.04192081, -0.71636402,  0.20420009,  0.22890795],
       [-0.74820647, -0.49756525,  0.20420009,  0.18310452],
       [-0.52792071, -0.71636402, -0.33697424, -0.38180445],
       ...,
       [-0.71149218, -0.43789285, -0.1902151 , -0.22912635],
       [-0.91342079, -0.45778365,  0.08495829,  0.22890795],
       [-0.41777783, -0.33843886, -0.01226964,  0.16783671]])

In [4]:
X_scaled.std(axis = 0)  # se escalan las variables para qeu guarden una misma scala

array([1., 1., 1., 1.])

In [5]:
df.iloc[2]

ArrDelay     14.0
DepDelay      8.0
Distance    515.0
AirTime      76.0
Name: 2, dtype: float64

In [6]:
X_scaled[2]

array([-0.52792071, -0.71636402, -0.33697424, -0.38180445])

In [7]:
# escalar minimo maximo
min_max_scaler = preprocessing.MinMaxScaler([0,10])
X_train_minmax = min_max_scaler.fit_transform(df)
X_train_minmax

array([[0.45335658, 0.01829826, 1.75524788, 1.96943973],
       [0.59285092, 0.1189387 , 1.75524788, 1.91850594],
       [0.69747167, 0.01829826, 1.09647164, 1.29032258],
       ...,
       [0.61028771, 0.14638609, 1.27512282, 1.46010187],
       [0.51438535, 0.13723696, 1.61009379, 1.96943973],
       [0.74978204, 0.19213175, 1.49173738, 1.90152801]])

In [8]:
# escalar por dummies, se entiende mas facilmente, pero consume mucha memoria

df = pd.read_csv("../../Tascas/Data/DelayedFlights.csv", nrows=100)
pd.get_dummies(df["Origin"])

IAD  IND  ISP  JAN  JAX  LAS
0     1    0    0    0    0    0
1     1    0    0    0    0    0
2     0    1    0    0    0    0
3     0    1    0    0    0    0
4     0    1    0    0    0    0
..  ...  ...  ...  ...  ...  ...
95    0    0    0    0    0    1
96    0    0    0    0    0    1
97    0    0    0    0    0    1
98    0    0    0    0    0    1
99    0    0    0    0    0    1

[100 rows x 6 columns]